# name: rust-docker

services:
  server:
    build:
      context: .
    image: ubunturust
    container_name: rust
    # faz o container ficar rodando
    stdin_open: true
    # working_dir: /app
    # command: "cargo install"
    restart: always
    volumes:
      - .:/app
    user: 1001:1001
